package Scanner.src;

import Scanner.src.Scanner;

public enum TokenType {
    UNKNOWN,
    OPEN_ROUND_BRACKET,
    CLOSE_ROUND_BRACKET,
    OPEN_SQUARE_BRACKET,
    CLOSE_SQUARE_BRACKET,
    OPEN_CURLY_BRACKET,
    CLOSE_CURLY_BRACKET,
    EQUALS,
    NOT_EQUALS,
    COMMA,
    SEMI_COLON,
    QUATATION_MARKS,
    EXCLAMATION_MARK,
    IDENTIFIER,
    END_OF_FILE



}
